blank_issues_enabled: true
contact_links:
  - name: Donaldmask Core Security Policy
    url: https://github.com/donaldmask/donaldmask/blob/master/SECURITY.md
    about: View security policy
  - name: Donaldmask Core Developers
    url: https://bitcoincore.org
    about: Donaldmask Core homepage
